name: Python CI

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Lint with black
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Check for README and LICENSE
        run: |
          test -f README.md
          test -f LICENSE

  release:
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from git tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create Release ZIP
        run: |
          zip -r dbus-huaweisun2000-pvinverter-v${VERSION}.zip . \
            -x '*.git*' \
            -x 'tests/*' \
            -x '.github/*' \
            -x '*.pyc' \
            -x '__pycache__/*' \
            -x '*.DS_Store'

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbus-huaweisun2000-pvinverter-v${{ env.VERSION }}
          path: dbus-huaweisun2000-pvinverter-v${{ env.VERSION }}.zip
